### ISSUE TITLE
Cannot find installed apps

### ISSUE THREAD

**Issue by 75rx** [eesposito/flatpak-run#1]
Steps to reproduce:
1. Install a flatpak (org.vim.Vim in my case)
2. do `fp vim`

Expected behavior: It should launch vim
Observed behavior: returns app not found

Vim launches fine when `flatpak run org.vim.Vim` is run.

System Info:
OS: Debain 12 stable
BASH version: 5.2.15(1)-release

**Comment by eesposito** [comment]
Thanks, the search should be fixed now.

If it's a CLI app it will have to be run with "-v" though. At least without modifying the script...

**Comment by 75rx** [comment]
> At least without modifying the script

I just wanted to change the code a little so it doesn't run the `flatpak list --app` operation everytime and instead,runs it once and stores the installed apps somewhere. Would've been less expensive on resources and maybe would have improved execution time.

Thanks for fixing the issue anyway.
